### ISSUE TITLE
Cannot install tds package if sitecore is on HTTPS!

### ISSUE THREAD

**Issue by mihaisava** [VGBenjamin/PackageInstaller#4]
Hello, 

I'm trying to install some tds packages on a sitecore installation that sits on HTTPS and I'm getting the following.

2016-07-12 10:34:22,951 [1] ERROR Sidewalk.SC.PackageInstaller.Client.Program [(null)] - An unexpected exception happend
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.GetResponse()
   at Sidewalk.SC.PackageInstaller.Client.Program.RequestTheHandler(String sitecoreWebUrl, String packagePath, Boolean acceptSsl) in C:\Projects\Sitecore\PackageInstaller\Sidewalk.SC.PackageInstaller.Client\Program.cs:line 401
2016-07-12 10:34:22,967 [1] ERROR Sidewalk.SC.PackageInstaller.Client.Program [(null)] - The request was aborted: Could not create SSL/TLS secure channel.

**Comment by mihaisava** [comment]
Full log

2016-07-12 10:34:22,951 [1] ERROR Sidewalk.SC.PackageInstaller.Client.Program [(null)] - An unexpected exception happend
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.GetResponse()
   at Sidewalk.SC.PackageInstaller.Client.Program.RequestTheHandler(String sitecoreWebUrl, String packagePath, Boolean acceptSsl) in C:\Projects\Sitecore\PackageInstaller\Sidewalk.SC.PackageInstaller.Client\Program.cs:line 401
2016-07-12 10:34:22,967 [1] ERROR Sidewalk.SC.PackageInstaller.Client.Program [(null)] - The request was aborted: Could not create SSL/TLS secure channel.
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.GetResponse()
   at Sidewalk.SC.PackageInstaller.Client.Program.RequestTheHandler(String sitecoreWebUrl, String packagePath, Boolean acceptSsl) in C:\Projects\Sitecore\PackageInstaller\Sidewalk.SC.PackageInstaller.Client\Program.cs:line 447
   at Sidewalk.SC.PackageInstaller.Client.Program.Main(String[] args) in C:\Projects\Sitecore\PackageInstaller\Sidewalk.SC.PackageInstaller.Client\Program.cs:line 258
2016-07-12 10:34:22,967 [1] ERROR Sidewalk.SC.PackageInstaller.Client.Program [(null)] - Unexpected exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sidewalk.SC.PackageInstaller.Client.Program.Main(String[] args) in C:\Projects\Sitecore\PackageInstaller\Sidewalk.SC.PackageInstaller.Client\Program.cs:line 333

**Comment by VGBenjamin** [comment]
Hello,

Did you already try to set the flag -acceptSsl ? 
If it isn't sufficient, could you try to add the following line in the if(acceptSs1) (line 391)
ServicePointManager.Expect100Continue = true;
ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3;

Benjamin
